<a href="https://colab.research.google.com/github/maanaav15369/ML-Projects/blob/main/Bengalore_house_price_predictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv('/content/Bengaluru_House_Data.csv')

In [3]:
data.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [5]:
data.shape

(13320, 9)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [7]:
for column in data.columns:
  print(data[column].value_counts())
  print("*"*20)

area_type
Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: count, dtype: int64
********************
availability
Ready To Move    10581
18-Dec             307
18-May             295
18-Apr             271
18-Aug             200
                 ...
16-Oct               1
17-Jan               1
16-Nov               1
16-Jan               1
14-Jul               1
Name: count, Length: 81, dtype: int64
********************
location
Whitefield                         540
Sarjapur  Road                     399
Electronic City                    302
Kanakpura Road                     273
Thanisandra                        234
                                  ...
3rd Stage Raja Rajeshwari Nagar      1
Chuchangatta Colony                  1
Electronic City Phase 1,             1
Chikbasavanapura                     1
Abshot Layout                        1
Name: count, Length: 1305, dtype: int64
********************
size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
10 BHK           2
11 Bedroom       2
27 BHK           1
19 BHK           1
43 Bedroom       1
16 BHK           1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64
********************
society
GrrvaGr    80
PrarePa    76
Sryalan    59
Prtates    59
GMown E    56
           ..
SLtalry     1
Rencyes     1
DiaveEn     1
Suiumy      1
Amionce     1
Name: count, Length: 2688, dtype: int64
********************
total_sqft
1200           843
1100           221
1500           205
2400           196
600            180
              ...
2920             1
5665.84          1
1369             1
7150             1
1200 - 1470      1
Name: count, Length: 2117, dtype: int64
********************
bath
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
11.0       3
13.0       3
16.0       2
27.0       1
14.0       1
40.0       1
15.0       1
18.0       1
Name: count, dtype: int64
********************
balcony
2.0    5113
1.0    4897
3.0    1672
0.0    1029
Name: count, dtype: int64
********************
price
75.00    310
65.00    302
55.00    275
60.00    270
45.00    240
        ...
43.04      1
61.11      1
46.56      1
42.54      1
47.35      1
Name: count, Length: 1994, dtype: int64
********************

In [8]:
data.isna().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [11]:
data.dropna(subset=['area_type','availability','society','balcony'],inplace=True)

In [13]:
data.describe()

              bath      balcony        price
count  7497.000000  7497.000000  7497.000000
mean      2.458450     1.629985    96.855674
std       0.881091     0.780087   105.375535
min       1.000000     0.000000     8.000000
25%       2.000000     1.000000    49.500000
50%       2.000000     2.000000    69.760000
75%       3.000000     2.000000   105.000000
max       9.000000     3.000000  2700.000000

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7497 entries, 0 to 13318
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     7497 non-null   object
 1   availability  7497 non-null   object
 2   location      7496 non-null   object
 3   size          7497 non-null   object
 4   society       7497 non-null   object
 5   total_sqft    7497 non-null   object
 6   bath          7497 non-null   float64
 7   balcony       7497 non-null   float64
 8   price         7497 non-null   float64
dtypes: float64(3), object(6)
memory usage: 585.7+ KB

In [17]:
data['location']=data['location'].fillna('Sarjapur Road')

In [18]:
data['size'].value_counts()

size
2 BHK        3411
3 BHK        3013
1 BHK         353
4 BHK         347
4 Bedroom     193
3 Bedroom     120
5 Bedroom      16
2 Bedroom      16
1 RK           10
5 BHK           9
6 BHK           3
6 Bedroom       3
11 BHK          1
9 BHK           1
7 BHK           1
Name: count, dtype: int64

In [20]:
data['size']=data['size'].fillna('2BHK')

In [21]:
data['bath']=data['bath'].fillna(data['bath'].median())

In [22]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7497 entries, 0 to 13318
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     7497 non-null   object
 1   availability  7497 non-null   object
 2   location      7497 non-null   object
 3   size          7497 non-null   object
 4   society       7497 non-null   object
 5   total_sqft    7497 non-null   object
 6   bath          7497 non-null   float64
 7   balcony       7497 non-null   float64
 8   price         7497 non-null   float64
dtypes: float64(3), object(6)
memory usage: 585.7+ KB

In [23]:
data['bhk']=data['size'].str.split().str.get(0).astype(int)

In [26]:
data[data.bhk > 20]

Empty DataFrame
Columns: [area_type, availability, location, size, society, total_sqft, bath, balcony, price, bhk]
Index: []

In [27]:
data['total_sqft'].unique()

array(['1056', '2600', '1521', ..., '1919', '2111', '4689'], dtype=object)

In [28]:
def convertRange(x):

  temp=x.split('-')
  if len(temp) == 2:
    return (float(temp[0]) + float(temp[1]))/2
  try:
    return float(x)
  except:
    return None

In [29]:
data['total_sqft']=data['total_sqft'].apply(convertRange)

In [30]:
data.head(

)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bhk
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056.0,2.0,1.0,39.07,2
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600.0,5.0,3.0,120.00,4
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521.0,3.0,1.0,95.00,3
5,Super built-up Area,Ready To Move,Whitefield,2 BHK,DuenaTa,1170.0,2.0,1.0,38.00,2
11,Plot Area,Ready To Move,Whitefield,4 Bedroom,Prrry M,2785.0,5.0,3.0,295.00,4

# price per square feet

In [38]:
data['price_per_sqft']=data['price']*100000 / data['total_sqft']

In [33]:
data['price_per_sqft']

0         3699.810606
1         4615.384615
3         6245.890861
5         3247.863248
11       10592.459605
             ...
13313     4237.918216
13314     6530.612245
13315     6689.834926
13317     5258.545136
13318    10407.336319
Name: price_per_sqft, Length: 7497, dtype: float64

In [34]:
data.describe()

,total_sqft,bath,balcony,price,bhk,price_per_sqft
count,7482.000000,7497.000000,7497.000000,7497.000000,7497.000000,7482.000000
mean,1507.528404,2.458450,1.629985,96.855674,2.529545,5991.975763
std,935.021386,0.881091,0.780087,105.375535,0.733199,9160.230760
min,11.000000,1.000000,0.000000,8.000000,1.000000,371.428571
25%,1115.000000,2.000000,1.000000,49.500000,2.000000,4279.387166
50%,1310.000000,2.000000,2.000000,69.760000,2.000000,5319.148936
75%,1656.000000,3.000000,2.000000,105.000000,3.000000,6696.579053
max,36000.000000,9.000000,3.000000,2700.000000,11.000000,672727.272727

In [35]:
data['location'].value_counts()

location
Whitefield          397
Sarjapur  Road      310
Electronic City     236
Kanakpura Road      216
Thanisandra         212
                   ...
Chikbasavanapura      1
Billamaranahalli      1
St. John's Road       1
Govindapura           1
Allalasandra          1
Name: count, Length: 635, dtype: int64

In [39]:
data['location']= data['location'].apply(lambda x: x.strip())
location_count=data['location'].value_counts()

In [43]:
location_count

location
Whitefield               398
Sarjapur  Road           310
Electronic City          238
Kanakpura Road           216
Thanisandra              215
                        ...
3rd Block Koramangala      1
Kuvempu Nagar              1
Mahalakshmi Puram          1
St. John's Road            1
Gulakamale                 1
Name: count, Length: 627, dtype: int64

In [40]:
location_count_less_10 = location_count[location_count<=10]
location_count_less_10

location
Arekere                  10
Rayasandra               10
BTM Layout               10
Sector 2 HSR Layout      10
Vidyaranyapura           10
                         ..
3rd Block Koramangala     1
Kuvempu Nagar             1
Mahalakshmi Puram         1
St. John's Road           1
Gulakamale                1
Name: count, Length: 484, dtype: int64

In [42]:
data['location']=data['location'].apply(lambda x: 'other' if x in location_count_less_10 else x)

In [44]:
data['location'].value_counts()

location
other                 1444
Whitefield             398
Sarjapur  Road         310
Electronic City        238
Kanakpura Road         216
                      ...
Neeladri Nagar          11
Marsur                  11
Parappana Agrahara      11
Karuna Nagar            11
Bharathi Nagar          11
Name: count, Length: 144, dtype: int64

# Outlier detection and removal

In [45]:
data.describe()

,total_sqft,bath,balcony,price,bhk,price_per_sqft
count,7482.000000,7497.000000,7497.000000,7497.000000,7497.000000,7482.000000
mean,1507.528404,2.458450,1.629985,96.855674,2.529545,5991.975763
std,935.021386,0.881091,0.780087,105.375535,0.733199,9160.230760
min,11.000000,1.000000,0.000000,8.000000,1.000000,371.428571
25%,1115.000000,2.000000,1.000000,49.500000,2.000000,4279.387166
50%,1310.000000,2.000000,2.000000,69.760000,2.000000,5319.148936
75%,1656.000000,3.000000,2.000000,105.000000,3.000000,6696.579053
max,36000.000000,9.000000,3.000000,2700.000000,11.000000,672727.272727

In [46]:
(data['total_sqft']/data['bhk']).describe()

count     7482.000000
mean       588.417067
std        224.951947
min          3.666667
25%        500.000000
50%        567.333333
75%        632.500000
max      11666.666667
dtype: float64

In [47]:
data = data[((data['total_sqft']/data['bhk']) >= 300)]
data.describe()

,total_sqft,bath,balcony,price,bhk,price_per_sqft
count,7440.000000,7440.000000,7440.000000,7440.000000,7440.000000,7440.000000
mean,1512.054101,2.458468,1.633065,96.956741,2.526882,5850.956214
std,935.394148,0.875590,0.780894,105.538459,0.727822,2705.289477
min,350.000000,1.000000,0.000000,10.000000,1.000000,371.428571
25%,1120.000000,2.000000,1.000000,49.952500,2.000000,4283.397683
50%,1312.000000,2.000000,2.000000,69.845000,2.000000,5321.395063
75%,1660.000000,3.000000,2.000000,105.000000,3.000000,6693.715009
max,36000.000000,9.000000,3.000000,2700.000000,11.000000,76530.612245

In [49]:
data.shape

(7440, 11)

In [50]:
data.price_per_sqft.describe()

count     7440.000000
mean      5850.956214
std       2705.289477
min        371.428571
25%       4283.397683
50%       5321.395063
75%       6693.715009
max      76530.612245
Name: price_per_sqft, dtype: float64

In [58]:
def remove_outliers_sqft(df):
    df_output = pd.DataFrame()
    for key,subdf in df.groupby('location'):
        m = np.mean(subdf.price_per)

        st=np.std(subdf.price_per_sqft)

        gen_df = subdf[(subdf.price_per_sqft > (m-st)) & (subdf.price_per_sqft <= (m+st))]
        df_output = pd.concat([df_output,gen_df],ignore_index=True)
    return df_output
    data = remove_outliers_sqft(data)

In [59]:
data.describe()

,total_sqft,bath,balcony,price,bhk,price_per_sqft
count,7440.000000,7440.000000,7440.000000,7440.000000,7440.000000,7440.000000
mean,1512.054101,2.458468,1.633065,96.956741,2.526882,5850.956214
std,935.394148,0.875590,0.780894,105.538459,0.727822,2705.289477
min,350.000000,1.000000,0.000000,10.000000,1.000000,371.428571
25%,1120.000000,2.000000,1.000000,49.952500,2.000000,4283.397683
50%,1312.000000,2.000000,2.000000,69.845000,2.000000,5321.395063
75%,1660.000000,3.000000,2.000000,105.000000,3.000000,6693.715009
max,36000.000000,9.000000,3.000000,2700.000000,11.000000,76530.612245

In [85]:
def bhk_outlier_remover(df):
    exclude_indices = np.array([])
    for location, location_df in df.groupby('location'):
        bhk_stats = {}
        for bhk, bhk_df in location_df.groupby('bhk'):
            bhk_stats[bhk] = {
                'mean': np.mean(bhk_df.price_per_sqft),
                'std': np.std(bhk_df.price_per_sqft),
                'count': bhk_df.shape[0]
            }
        for bhk, bhk_df in location_df.groupby('bhk'):
            stats = bhk_stats.get(bhk - 1)
            if stats and stats['count'] > 5:
                exclude_indices = np.append(exclude_indices, bhk_df[bhk_df.price_per_sqft < (stats['mean'])].index.values)
    return df.drop(exclude_indices, axis='index')

In [62]:
data=bhk_outlier_remover(data)

In [63]:
data

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bhk,price_per_sqft
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056.0,2.0,1.0,39.07,2,3699.810606
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600.0,5.0,3.0,120.00,4,4615.384615
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521.0,3.0,1.0,95.00,3,6245.890861
5,Super built-up Area,Ready To Move,Whitefield,2 BHK,DuenaTa,1170.0,2.0,1.0,38.00,2,3247.863248
11,Plot Area,Ready To Move,Whitefield,4 Bedroom,Prrry M,2785.0,5.0,3.0,295.00,4,10592.459605
...,...,...,...,...,...,...,...,...,...,...,...
13313,Super built-up Area,Ready To Move,Uttarahalli,3 BHK,Aklia R,1345.0,2.0,1.0,57.00,3,4237.918216
13314,Super built-up Area,Ready To Move,Green Glen Layout,3 BHK,SoosePr,1715.0,3.0,3.0,112.00,3,6530.612245
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453.0,4.0,0.0,231.00,5,6689.834926
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141.0,2.0,1.0,60.00,2,5258.545136
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689.0,4.0,1.0,488.00,4,10407.336319

In [65]:
data.shape

(7438, 11)

In [67]:
data.drop(columns=['size','price_per_sqft'],inplace=True)

#cleaned data

In [68]:
data.head()

,area_type,availability,location,society,total_sqft,bath,balcony,price,bhk
0,Super built-up Area,19-Dec,Electronic City Phase II,Coomee,1056.0,2.0,1.0,39.07,2
1,Plot Area,Ready To Move,Chikka Tirupathi,Theanmp,2600.0,5.0,3.0,120.00,4
3,Super built-up Area,Ready To Move,Lingadheeranahalli,Soiewre,1521.0,3.0,1.0,95.00,3
5,Super built-up Area,Ready To Move,Whitefield,DuenaTa,1170.0,2.0,1.0,38.00,2
11,Plot Area,Ready To Move,Whitefield,Prrry M,2785.0,5.0,3.0,295.00,4

In [69]:
data.to_csv("cleaned_data.csv")

In [70]:
x=data.drop(columns=['price'])
y=data['price']

In [72]:
#importing importent libraries
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [93]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    x, y,
    test_size=0.2,
    random_state=42
)

In [74]:
print(X_train.shape)
print(X_test.shape)

(5950, 8)
(1488, 8)

#applying Linear Regression

In [82]:
column_trans=make_column_transformer((OneHotEncoder(sparse_output=False),['location','area_type','availability','society']),
                                    remainder='passthrough')

In [77]:
scaler = StandardScaler()

In [79]:
lr =LinearRegression()

In [96]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LinearRegression

categorical_cols = ['location', 'area_type', 'availability', 'society']

column_trans = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False),
         categorical_cols)
    ],
    remainder='passthrough'
)

pipe = make_pipeline(
    column_trans,
    StandardScaler(),
    LinearRegression()
)

In [98]:
pipe.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['location', 'area_type',
                                                   'availability',
                                                   'society'])])),
                ('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression())])

In [87]:
print(X_train.dtypes)

area_type        object
availability     object
location         object
society          object
total_sqft      float64
bath            float64
balcony         float64
bhk               int64
dtype: object

In [88]:
print(X_train['area_type'].unique())

['Built-up  Area' 'Super built-up  Area' 'Plot  Area' 'Carpet  Area']

In [89]:
print(X_train.columns.tolist())
print(X_train.dtypes)

['area_type', 'availability', 'location', 'society', 'total_sqft', 'bath', 'balcony', 'bhk']
area_type        object
availability     object
location         object
society          object
total_sqft      float64
bath            float64
balcony         float64
bhk               int64
dtype: object

In [95]:
print(column_trans)

ColumnTransformer(remainder='passthrough',
                  transformers=[('cat',
                                 OneHotEncoder(handle_unknown='ignore',
                                               sparse_output=False),
                                 ['location', 'area_type'])])

In [99]:
y_pred_lr=pipe.predict(X_test)

In [100]:
r2_score(y_test,y_pred_lr)

0.733113372295598

#applying lasso

In [101]:
lasso =Lasso()

In [102]:
pipe= make_pipeline(column_trans,scaler,lasso)

In [103]:
pipe.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['location', 'area_type',
                                                   'availability',
                                                   'society'])])),
                ('standardscaler', StandardScaler()), ('lasso', Lasso())])

In [104]:
y_pred_lasso = pipe.predict(X_test)
r2_score(y_test,y_pred_lasso)

0.7272136596984606

#Applying Ridge

In [105]:
ridge =Ridge()

In [106]:
pipe = make_pipeline(column_trans,scaler,ridge)

In [107]:
pipe.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['location', 'area_type',
                                                   'availability',
                                                   'society'])])),
                ('standardscaler', StandardScaler()), ('ridge', Ridge())])

In [108]:
y_pred_ridge = pipe.predict(X_test)
r2_score(y_test,y_pred_ridge)

0.7334157272987843

In [109]:
print("No Regularization:",r2_score(y_test,y_pred_lr))
print("Lasso:",r2_score(y_test,y_pred_lasso))
print("Ridge:",r2_score(y_test,y_pred_ridge))

No Regularization: 0.733113372295598
Lasso: 0.7272136596984606
Ridge: 0.7334157272987843

In [112]:
import pickle
pickle.dump(pipe,open('RidgeModel.pkl','wb'))